### PR TITLE
Upgrade Node to v10.16.3

### PR DESCRIPTION
**Pull request by katstevens**
https://trello.com/c/jaDeKZlt/1079-update-node

Node 8 is reaching end of life. Let's upgrade to the LTS of Node v10 (see https://nodejs.org/en/download/).

### CODE REVIEW

**Comment by lfdebrux** [comment]
Oooh. Did it work?

**Comment by katstevens** [comment]
@lfdebrux Yarn does all the heavy lifting in the gulpfile; it seems completely unbothered.

**Comment by lfdebrux** [comment]
While we're at it, we could upgrade yarn?

**Comment by lfdebrux** [comment]
I tried building digitalmarketplace-buyer-frontend using this version of frontend-base, got a whole bunch of errors :(

Screen Shot 2019-09-02 at 11 37 34

**Comment by katstevens** [comment]
@lfdebrux Interesting, I was trying it out on Admin FE with a local installation of `node@10`

**Comment by lfdebrux** [comment]
Doing a `yarn upgrade` against buyer frontend fixed it, so I think this upgrade will work!

**Comment by aliuk2012** [comment]
Why do we need `yarn` and not just use Nodes native `npm`?

**Comment by katstevens** [comment]
@aliuk2012 We used to have `bower` managing our assets etc, I think we replaced like-for-like with `yarn`.

**Pull request merged**
