### PR TITLE
Update pinned dependencies

### PR DESCRIPTION
**Pull request by lfdebrux**
Trello ticket: https://trello.com/c/1OxhYlQB/1118-update-pinned-dependencies-in-docker-base

### Update awscli from 1.14.31 to 1.16.239

Changelog: https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst

### Update awscli-cwlogs from 1.4.4 to 1.4.5

Changelog: :shrug:

### Update supervisor from 3.3.3 to 3.4.0

Changelog:

  - [3.4.0](http://supervisord.org/changes.html#id6)
  - [3.3.5](http://supervisord.org/changes.html#id7)
  - [3.3.4](http://supervisord.org/changes.html#id8)

### Update uWSGI from 2.0.15 to 2.0.18

Changelog:

  - [2.0.18](https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.18.html)
  - [2.0.17.1](https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.17.1.html)
  - [2.0.17](https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.17.html)
  - [2.0.16](https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.16.html)

### CODE REVIEW

**Comment by katstevens** [comment]
Have created a card to investigate: https://trello.com/c/Rbri4tFF/1048-ci-check-for-our-docker-base-repo

**Comment by lfdebrux** [comment]
> What would be a sensible CI check for this repo? Could we feasibly ask Travis to build a test container from the image?

Yeah that should work 🤔

**Comment by lfdebrux** [comment]
I've built the image locally with success

**Comment by lfdebrux** [comment]
I've tested this with the buyer frontend on PaaS and it seems to work, going to merge.

**Pull request merged**
