### PR TITLE
nginx log output: switch to using X-B3-TraceId request header for requestId & add further zipkin headers

### PR DESCRIPTION
**Pull request by risicle**
https://trello.com/c/Re7CUjj7/329-ensure-nginx-emits-request-id-in-logs-even-in-error-cases

`X-B3-TraceId` has the advantage over using an upstream response header in that we receive it even if the upstream application isn't responding properly.

Also adding further zipkin headers to kill two birds with one stone. :bird: :moyai: :duck:

### CODE REVIEW

**Comment by katstevens** [comment]
Would replacing the `requestID` count as a breaking change? (Genuine question - I have no idea if anything actually relies on it being there)

**Comment by risicle** [comment]
I *don't yet know*, which is why I'm playing it safe for now. Certainly if I did that I'd need to make sure I switched all our services at the same time.

**Comment by risicle** [comment]
Yeah, just to make this clear, this PR takes the conservative approach and *doesn't* change any existing log field names, though I am going to switch it to remove the leading `tracing` from the new ones.

**Comment by risicle** [comment]
http://nginx.org/en/docs/http/ngx_http_core_module.html#var_http_

Not a great sign that we only have one, maybe two people who feel they understand this enough to approve.

**Pull request merged**
