### PR TITLE
supervisord: send SIGUSR1 to uwsgi instead of SIGINT

### PR DESCRIPTION
**Pull request by risicle**
https://trello.com/c/skD666lL/
https://trello.com/c/PyDaRXEj/

It appears that using `--hook-master-start` can only let you *add* actions to a handler - it won't stop `uwsgi` doing its default *as well*, which in the case of `SIGINT` is brutal death.

The only "default" thing `SIGUSR1` does in `uwsgi` is "print statistics".

### CODE REVIEW

**Comment by lfdebrux** [comment]
Has this been tested on staging now?

**Comment by risicle** [comment]
No. I'm going via the front door at the moment and taking these through the pipeline.

**Comment by lfdebrux** [comment]
> No. I'm going via the front door at the moment and taking these through the pipeline.

I'd rather you do some testing before merging, as this issue report https://github.com/unbit/uwsgi/issues/1795 suggests there might be also an issue inherent in how uwsgi closes requests.

**Comment by risicle** [comment]
I've been doing a lot of testing before merging thanks - I just decided to make a small suggested change before merging just now and it turned out to be less innocuous than it seemed.

**Comment by risicle** [comment]
And TBH, even if it does encounter that bug, it actually wouldn't be _any_ worse than the current way our instances handle shutdowns.

**Comment by lfdebrux** [comment]
> I've been doing a lot of testing before merging thanks - that was my thursday and friday - I just decided to make a small suggested change before merging just now and it turned out to be less innocuous than it seemed.

If we know it works with SIGHUP then I'd rather go with that than use USR1 without testing.

**Comment by risicle** [comment]
`SIGHUP` is indeed useful so it would be good to preserve that. And I'm not suggesting going to production without testing, but it takes me a good hour to get the hack for an unmerged experimental image together and onto staging - and there aren't that many hours remaining today.

**Pull request merged**
